
project_id = "adhegezdzqlnqqnymvps"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-convert-upload]
verify_jwt = false
