
// Removed import { Address } from "@/services/AddressService"; 
// It was causing an error and SavedAddress is more specific here.

export type ShipmentStatus =
  | 'pending_rates' // Initial status, waiting for rates
  | 'rates_fetched' // Rates have been fetched
  | 'rate_selected' // User has selected a rate
  | 'label_purchased' // Label has been purchased (but not necessarily batch-processed yet)
  | 'error' // An error occurred with this shipment
  | 'failed' // Label creation failed for this shipment
  | 'completed'; // Label successfully created and included in results (e.g., part of a batch)

export interface PackageDetails {
  length: number;
  width: number;
  height: number;
  weight: number;
  value?: number;
  currency?: string;
}

export interface ShipmentDetails {
  id: string; // Ensure ID is string for consistency
  // Recipient Address
  recipient: string; // Typically name
  customer_name?: string;
  street1: string;
  street2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  phone?: string;
  email?: string; 
  is_residential?: boolean; 

  // Package Details
  weight: number; // in ounces or a consistent unit
  length: number;
  width: number;
  height: number;
  value?: number;
  currency?: string;

  // Service Details (optional, might be populated after rate selection)
  carrier?: string;
  service?: string;
  rate?: number;
  selectedRateId?: string | null;
  
  // Metadata
  reference?: string; // User-defined reference (e.g., order number)
  notes?: string;
}

export interface Rate {
  id: string;
  carrier: string;
  service: string;
  rate: string; // Rate from API is often string
  delivery_days?: number;
  currency: string;
}

export interface BulkShipment extends ShipmentDetails {
  row?: number; // Original row from CSV for easy reference
  status?: ShipmentStatus;
  availableRates?: Rate[];
  easypost_id?: string; // EasyPost shipment ID (shp_...)
  // selected_rate_id is deprecated in favor of selectedRateId
  selectedRateId?: string | null; // EasyPost rate ID (rate_...)
  label_url?: string; // URL for individual PNG label (legacy or specific use)
  label_urls?: { // Preferred structure for multiple formats
    png?: string;
    pdf?: string;
    zpl?: string;
    epl?: string; // Added EPL
  };
  tracking_code?: string;
  tracking_number?: string; // Alias for tracking_code
  isFetchingRates?: boolean; // To indicate if rates are currently being fetched for this specific shipment
  // rate property in ShipmentDetails is the selected rate cost (number)
  details?: any; // For any other miscellaneous details, like error messages from rate fetching
  customer_address?: string; // Often a concatenation for display
}


export interface ConsolidatedLabelUrls {
  pdf?: string;
  zpl?: string;
  epl?: string;
  pdfZip?: string; // Link to a ZIP file of all PDFs
  zplZip?: string; // Link to a ZIP file of all ZPLs
  eplZip?: string; // Link to a ZIP file of all EPLs
}

export interface BatchResult {
  batchId: string;
  consolidatedLabelUrls: ConsolidatedLabelUrls;
  scanFormUrl?: string | null; // URL for the generated scan form/manifest
  status?: string; // e.g., "creating", "completed", "failed"
  labelCount?: number;
}

export interface BulkUploadResult {
  total: number; 
  successful: number; 
  failed: number; 
  totalCost?: number; 
  processedShipments: BulkShipment[];
  failedShipments?: Array<{ shipmentId?: string; error: string; row?: number; details?: any }>;
  batchResult?: BatchResult | null; 
  uploadStatus?: UploadStatus; 
  pickupAddress?: SavedAddress; 
  bulk_label_png_url?: string; // Deprecated if using consolidatedLabelUrls
  bulk_label_pdf_url?: string; // Deprecated if using consolidatedLabelUrls
  isFetchingRates?: boolean; // Indicates if rates are being fetched for the whole batch
}

export type UploadStatus =
  | 'idle'
  | 'uploading' // File is being uploaded/parsed by client
  | 'processing' // File parsed, server is creating shipments/fetching rates
  | 'editing' // Rates fetched, user is editing/selecting rates
  | 'creating-labels' // Labels are actively being generated by server
  | 'success' // Labels generated and available
  | 'error'; // An error occurred in the process


export interface SavedAddress {
  id: string; 
  user_id?: string; 
  name?: string;
  company?: string;
  street1: string;
  street2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  phone?: string;
  email?: string; // Ensure this is here for forms
  is_residential?: boolean; // Ensure this is here for forms
  is_default_from?: boolean;
  is_default_to?: boolean;
  created_at?: string;
  updated_at?: string;
  address_type?: 'residential' | 'business'; 
  instructions?: string; 
}

export const CARRIER_OPTIONS: { label: string; value: string }[] = [
  { label: 'All Carriers', value: '' },
  { label: 'USPS', value: 'USPS' },
  { label: 'UPS', value: 'UPS' },
  { label: 'FedEx', value: 'FedEx' },
  { label: 'DHL Express', value: 'DHLExpress' },
  // Add more carriers dynamically based on available rates if needed
];

export type ShippingStep = 'address' | 'parcel' | 'rates' | 'payment' | 'label'; // Example steps

export interface ShippingWorkflowStep { // Example structure
  id: ShippingStep;
  name: string;
  status: 'current' | 'upcoming' | 'complete' | 'error';
}

